#############################################################################
# Makefile for building: mole.app/Contents/MacOS/mole
# Generated by qmake (2.01a) (Qt 4.8.2) on: Sat Aug 25 13:23:31 2012
# Project:  mole.pro
# Template: app
# Command: /usr/local/bin/qmake -spec /usr/local/Cellar/qt/4.8.2/mkspecs/macx-g++ -o Makefile mole.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -O2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
INCPATH       = -I/usr/local/Cellar/qt/4.8.2/mkspecs/macx-g++ -I. -I/usr/local/Cellar/qt/4.8.2/lib/QtCore.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.2/lib/QtCore.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.2/lib/QtGui.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.2/lib/QtGui.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.2/include -Iinclude -I. -I. -F/usr/local/Cellar/qt/4.8.2/lib
LINK          = g++
LFLAGS        = -headerpad_max_install_names -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5
LIBS          = $(SUBLIBS) -F/usr/local/Cellar/qt/4.8.2/lib -L/usr/local/Cellar/qt/4.8.2/lib -L/Users/stepan/Development/mole2/mole/lib/ -lmole-engine -framework QtGui -L/usr/local/Cellar/qt/4.8.2/lib -F/usr/local/Cellar/qt/4.8.2/lib -framework QtCore 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /usr/local/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		moc_mainwindow.o
DIST          = /usr/local/Cellar/qt/4.8.2/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/common/gcc-base-macx.conf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/common/g++-base.conf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/common/g++-macx.conf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/4.8.2/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/release.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/mac/x86_64.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/lex.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/include_source_dir.prf \
		mole.pro
QMAKE_TARGET  = mole
DESTDIR       = 
TARGET        = mole.app/Contents/MacOS/mole

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-arch \
		x86_64 \
		-Xarch_x86_64 \
		-mmacosx-version-min=10.5 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile mole.app/Contents/PkgInfo mole.app/Contents/Resources/empty.lproj mole.app/Contents/Info.plist $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) mole.app/Contents/MacOS/ || $(MKDIR) mole.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: mole.pro  /usr/local/Cellar/qt/4.8.2/mkspecs/macx-g++/qmake.conf /usr/local/Cellar/qt/4.8.2/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/common/gcc-base-macx.conf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/common/g++-base.conf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/common/g++-macx.conf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/4.8.2/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/release.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/mac/x86_64.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/lex.prf \
		/usr/local/Cellar/qt/4.8.2/mkspecs/features/include_source_dir.prf \
		/usr/local/Cellar/qt/4.8.2/lib/QtGui.framework/QtGui.prl \
		/usr/local/Cellar/qt/4.8.2/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec /usr/local/Cellar/qt/4.8.2/mkspecs/macx-g++ -o Makefile mole.pro
/usr/local/Cellar/qt/4.8.2/mkspecs/common/unix.conf:
/usr/local/Cellar/qt/4.8.2/mkspecs/common/mac.conf:
/usr/local/Cellar/qt/4.8.2/mkspecs/common/gcc-base.conf:
/usr/local/Cellar/qt/4.8.2/mkspecs/common/gcc-base-macx.conf:
/usr/local/Cellar/qt/4.8.2/mkspecs/common/g++-base.conf:
/usr/local/Cellar/qt/4.8.2/mkspecs/common/g++-macx.conf:
/usr/local/Cellar/qt/4.8.2/mkspecs/qconfig.pri:
/usr/local/Cellar/qt/4.8.2/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Cellar/qt/4.8.2/mkspecs/features/qt_functions.prf:
/usr/local/Cellar/qt/4.8.2/mkspecs/features/qt_config.prf:
/usr/local/Cellar/qt/4.8.2/mkspecs/features/exclusive_builds.prf:
/usr/local/Cellar/qt/4.8.2/mkspecs/features/default_pre.prf:
/usr/local/Cellar/qt/4.8.2/mkspecs/features/mac/default_pre.prf:
/usr/local/Cellar/qt/4.8.2/mkspecs/features/release.prf:
/usr/local/Cellar/qt/4.8.2/mkspecs/features/default_post.prf:
/usr/local/Cellar/qt/4.8.2/mkspecs/features/mac/default_post.prf:
/usr/local/Cellar/qt/4.8.2/mkspecs/features/mac/x86_64.prf:
/usr/local/Cellar/qt/4.8.2/mkspecs/features/mac/objective_c.prf:
/usr/local/Cellar/qt/4.8.2/mkspecs/features/warn_on.prf:
/usr/local/Cellar/qt/4.8.2/mkspecs/features/qt.prf:
/usr/local/Cellar/qt/4.8.2/mkspecs/features/unix/thread.prf:
/usr/local/Cellar/qt/4.8.2/mkspecs/features/moc.prf:
/usr/local/Cellar/qt/4.8.2/mkspecs/features/mac/rez.prf:
/usr/local/Cellar/qt/4.8.2/mkspecs/features/mac/sdk.prf:
/usr/local/Cellar/qt/4.8.2/mkspecs/features/resources.prf:
/usr/local/Cellar/qt/4.8.2/mkspecs/features/uic.prf:
/usr/local/Cellar/qt/4.8.2/mkspecs/features/yacc.prf:
/usr/local/Cellar/qt/4.8.2/mkspecs/features/lex.prf:
/usr/local/Cellar/qt/4.8.2/mkspecs/features/include_source_dir.prf:
/usr/local/Cellar/qt/4.8.2/lib/QtGui.framework/QtGui.prl:
/usr/local/Cellar/qt/4.8.2/lib/QtCore.framework/QtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/local/Cellar/qt/4.8.2/mkspecs/macx-g++ -o Makefile mole.pro

mole.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) mole.app/Contents || $(MKDIR) mole.app/Contents 
	@$(DEL_FILE) mole.app/Contents/PkgInfo
	@echo "APPL????" >mole.app/Contents/PkgInfo
mole.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) mole.app/Contents/Resources || $(MKDIR) mole.app/Contents/Resources 
	@touch mole.app/Contents/Resources/empty.lproj
	
mole.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) mole.app/Contents || $(MKDIR) mole.app/Contents 
	@$(DEL_FILE) mole.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,mole,g" -e "s,@TYPEINFO@,????,g" /usr/local/Cellar/qt/4.8.2/mkspecs/macx-g++/Info.plist.app >mole.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) .tmp/mole1.0.0 || $(MKDIR) .tmp/mole1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/mole1.0.0/ && $(COPY_FILE) --parents mainwindow.h include/mole-engine/mole-engine-test-suite.h include/mole-engine/mole-engine.h include/seg/Segy.h include/shared/config.h include/shared/common.h .tmp/mole1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp .tmp/mole1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/mole1.0.0/ && (cd `dirname .tmp/mole1.0.0` && $(TAR) mole1.0.0.tar mole1.0.0 && $(COMPRESS) mole1.0.0.tar) && $(MOVE) `dirname .tmp/mole1.0.0`/mole1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/mole1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r mole.app
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: mainwindow.h
	/usr/local/Cellar/qt/4.8.2/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ mainwindow.h -o moc_mainwindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/usr/local/Cellar/qt/4.8.2/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

